{{ $activeProfiles := .Values.activeProfiles }}
{{ $mysqlUrl := .Values.local.mysql.url }}
{{ $mysqlUsername := .Values.local.mysql.username }}
{{ $mysqlPassword := .Values.local.mysql.password }}
{{ $jaegerHost := .Values.local.jaeger.host }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-item-{{ $activeProfiles }}
  labels:
    app: sample-item-{{ $activeProfiles }}
data:
  TZ: Asia/Taipei
  activeProfiles: {{ $activeProfiles }}
  application.yml: |-
    spring:
      profiles: {{ $activeProfiles }}
      datasource:
        url: {{ $mysqlUrl }}
        username: {{ $mysqlUsername }}
        password: {{ $mysqlPassword }}
