{{ $activeProfiles := .Values.activeProfiles }}

apiVersion: v1
kind: Service
metadata:
  name: sample-item
  labels:
    app: sample-item-{{ $activeProfiles }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9527
  selector:
    app: sample-item-{{ $activeProfiles }}
