apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-item-route
spec:
  hosts:
    - sample-item
  http:
    - route:
      - destination:
          host: sample-item
          subset: v1
        weight: 50
      - destination:
          host: sample-item
          subset: v2
        weight: 50
