apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - sample-gateway
  http:
  - match:
    - uri:
        prefix: /member
    - uri:
        prefix: /item
    route:
    - destination:
        host: sample-pt-gw
        port:
          number: 80
