{{ $activeProfiles := .Values.activeProfiles }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-task
  labels:
    app: sample-task-{{ $activeProfiles }}
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-task-{{ $activeProfiles }}
      version: v1
  template:
    metadata:
      labels:
        app: sample-task-{{ $activeProfiles }}
        version: v1
    spec:
      containers:
        - name: sample-task
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: sample-task-{{ $activeProfiles }}
            - name: activeProfiles
              valueFrom:
                configMapKeyRef:
                  key: activeProfiles
                  name: sample-task-{{ $activeProfiles }}
          image: jianminhuang/sample-task:1
          imagePullPolicy: Always
