{{ $activeProfiles := .Values.activeProfiles }}

apiVersion: v1
kind: Service
metadata:
  name: sample-task
  labels:
    app: sample-task-{{ $activeProfiles }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9987
  selector:
    app: sample-task-{{ $activeProfiles }}
