spring:
  profiles: ide
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
opentracing:
  jaeger:
    udp-sender:
      host: localhost
