spring:
  profiles: local
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
opentracing:
  jaeger:
    udp-sender:
      host: localhost

---

spring:
  profiles: k8s
  rabbitmq:
    host: sample-rabbitmq
    username: rabbitmq
    password: rabbitmq
  datasource:
    url: jdbc:mysql://sample-mysql:3306/test?useSSL=false
    username: root
    password: 1qaz2wsx
opentracing:
  jaeger:
    udp-sender:
      host: jaeger-agent