{{ $activeProfiles := .Values.activeProfiles }}
{{ $hostSampleItem := .Values.local.host.sample.item }}
{{ $hostSampleMember := .Values.local.host.sample.member }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-lg-gw-{{ $activeProfiles }}
  labels:
    app: sample-lg-gw-{{ $activeProfiles }}
data:
  TZ: Asia/Taipei
  activeProfiles: {{ $activeProfiles }}
  application.yml: |-
    spring:
      profiles: {{ $activeProfiles }}
    host:
      sample:
        item: {{ $hostSampleItem }}
        member: {{ $hostSampleMember }}
