{{ $activeProfiles := .Values.activeProfiles }}

apiVersion: v1
data:
  TZ: Asia/Taipei
  activeProfiles: {{ $activeProfiles }}
kind: ConfigMap
metadata:
  labels:
    app: sample-member-{{ $activeProfiles }}
  name: sample-member-config
