apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sample-member
spec:
  host: sample-member
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v3
    labels:
      version: v3