{{ $activeProfiles := .Values.activeProfiles }}

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-member-{{ $activeProfiles }}
    service: sample-member-{{ $activeProfiles }}
  name: sample-member
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9800
  selector:
    app: sample-member-{{ $activeProfiles }}
