spring:
  profiles: local
host:
  sample:
    lg:
      gw: "http://127.0.0.1:9999"
opentracing:
  jaeger:
    udp-sender:
      host: localhost

---

spring:
  profiles: k8s
host:
  sample:
    lg:
      gw: "http://sample-lg-gw"
opentracing:
  jaeger:
    udp-sender:
      host: jaeger-agent