{{ $activeProfiles := .Values.activeProfiles }}

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-lg-gw-{{ $activeProfiles }}
    service: sample-lg-gw-{{ $activeProfiles }}
  name: sample-lg-gw
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9999
  selector:
    app: sample-lg-gw-{{ $activeProfiles }}
