spring:
  profiles: local
host:
  sample:
    item: "http://127.0.0.1:9527"
    member: "http://127.0.0.1:9876"

---

spring:
  profiles: k8s
host:
  sample:
    item: "http://sample-item"
    member: "http://sample-member"