spring:
  profiles: local
host:
  sample:
    item: "http://127.0.0.1:9527"
    member: "http://127.0.0.1:9800"
opentracing:
  jaeger:
    udp-sender:
      host: localhost

---

spring:
  profiles: k8s
host:
  sample:
    item: "http://sample-item"
    member: "http://sample-member"
opentracing:
  jaeger:
    udp-sender:
      host: jaeger-agent