{{ $activeProfiles := .Values.activeProfiles }}

apiVersion: v1
kind: Service
metadata:
  name: sample-member
  labels:
    app: sample-member-{{ $activeProfiles }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9800
  selector:
    app: sample-member-{{ $activeProfiles }}
